name: NexaCloud Multi-Env Orchestrator

on:
  push:
    branches:
      - dev
      - testing
      - main # Used for production

#  THIS BLOCK TO FIX THE SECURITY PERMISSIONS BLOCKER
permissions:
  id-token: write   # Required to allow the reusable workflow to request OIDC tokens
  contents: read    # Required to let actions checkout your code repos
  actions: write     # Required if the reusable workflow manages internal execution steps      

jobs:
  # Dev Pipeline Run
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/nexacloud-reusable.yml
    with:
      environment: dev
      aws_region: eu-west-1
      eks_cluster: nexacloud-dev-cluster
      namespace: nexacloud-dev
    secrets: inherit

  # Testing Pipeline Run
  deploy-testing:
    if: github.ref == 'refs/heads/testing'
    uses: ./.github/workflows/nexacloud-reusable.yml
    with:
      environment: testing
      aws_region: eu-west-1
      eks_cluster: nexacloud-testing-cluster
      namespace: nexacloud-testing
    secrets: inherit

  # Production Pipeline Run
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/nexacloud-reusable.yml
    with:
      environment: prod
      aws_region: eu-west-1
      eks_cluster: nexacloud-prod-cluster
      namespace: nexacloud
    secrets: inherit
