name: NexaCloud Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment name (dev, staging, prod)'
        required: true
        type: string
      aws_region:
        description: 'Target AWS deployment region'
        required: false
        type: string
        default: 'eu-west-1'
      eks_cluster:
        description: 'Name of your target EKS cluster'
        required: true
        type: string
      namespace:
        description: 'Target Kubernetes namespace'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  code_quality_stage:
    name: Quality Phase (${{ inputs.environment }})
    uses: ./.github/workflows/code-quality-fragment.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy_stage:
    name: Deployment Phase (${{ inputs.environment }})
    needs: code_quality_stage
    uses: ./.github/workflows/deploy-fragment.yaml
    with:
      environment: ${{ inputs.environment }}
      aws_region: ${{ inputs.aws_region }}
      eks_cluster: ${{ inputs.eks_cluster }}
      namespace: ${{ inputs.namespace }}
      image_tag: ${{ needs.code_quality_stage.outputs.image_tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      GRAFANA_LOKI_URL: ${{ secrets.GRAFANA_LOKI_URL }}
